### ISSUE TITLE
Don't show a link to the sidebar header in each page ToC

### ISSUE THREAD

**Issue by recvfrom** [Drassil/git-wiki#32] opened 2018-09-28 15:45 UTC
Thanks for making this!  I'm trying it out for a personal wiki instance

Is it by design that the sidebar header shows up in each pages ToC?  Personally I find this kinda confusing, since you'd expect the ToC to just show links to things on the actual "wiki" page.

This functionality is visible in the example: http://www.drassil.org/git-wiki/#git_wiki_demo

**Comment by Yehonal** [comment] 2018-10-01 11:05
Sorry i didn't understand which is your issue exactly

could you post a screenshot highlighting which ToC are you referring?

The left sidebar is always visible in each page by design and the ToC, at the top of the page, appears when a page contains more than 3 headers (<hX> tag) and it's different for each page.

**Comment by recvfrom** [comment] 2018-10-01 14:17
Sorry for the confusion - here's a screenshot:

<img width="858" alt="gitwiki" src="https://user-images.githubusercontent.com/36489577/46294050-f30d4480-c562-11e8-9c61-c3c741e7d1ec.png">

It looks like the h1 tag from the sidebar gets included when the ToC searches for hX tags

**Comment by Yehonal** [comment] 2018-10-17 11:50
Fixed in https://github.com/Drassil/git-wiki/commit/cf30d666a7a67d3634cb97c17de2f4927a15ea8a

thank you for reporting it!

**Closed by Yehonal** 2018-10-17 11:50 UTC
